### ISSUE TITLE
how to install on RaspPi4

### ISSUE THREAD

**Issue by Exclution** [seborama/pcloud#5]
Dear Seb, 

can you please add a short installation howto - cause standard installation procedure is not working on my rasppi4.
thanks!

**Comment by seborama** [comment]
Hi, sorry I've been busy this week. Will try and check tomorrow.
What exactly was your issue on the pi4?

**Comment by Exclution** [comment]
Hi @seborama , thanks for your reply. im looking for a step-by-step howto how to install this on RaspPi4 for non pro's :-)
f. e. how to install "go`"?

**Comment by seborama** [comment]
Hi,

This project uses golang but it does not ain to teach Go 😉

I can suggest the main golang web site:

https://golang.org

Regards
